# NumPy

In [1]:
import numpy as np

In [2]:
L1 = [1,2,3,4,5,6,7,8]# Crear una lista

In [3]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x2 = np.array(L1, dtype='float32')
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64 (+/-999.9999999e99999)
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_) 

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3,12,dtype=np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [10]:
np.linspace(1., 7., 12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
x.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
x.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.resize(x, (5, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios
1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz 4x4 con los valores desde 0 hasta 15.
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matrix 5x4
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme

## Propiedades de los arrays

In [5]:
import numpy as np
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
x.ndim

2

In [7]:
x.shape

(3, 4)

In [27]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
x.ndim

2

In [30]:
x.shape

(3, 4)

In [31]:
x.size

12

In [32]:
x.dtype

dtype('int64')

In [33]:
x.itemsize

8

In [34]:
x.data

In [35]:
x[2]

array([ 8,  9, 10, 11])

In [36]:
x[2,1]

9

In [37]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [39]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
y[3:8]

array([3, 4, 5, 6, 7])

In [41]:
y[1:7:2]

array([1, 3, 5])

In [42]:
z = np.arange(10, 6, -1)
z

array([10,  9,  8,  7])

In [43]:
y[z]

array([10,  9,  8,  7])

In [44]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [47]:
cond = (x < 25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [48]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
x.dtype

dtype('int64')

In [52]:
x[5] = 3.1415
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
x[8] = 1.2j 

TypeError: can't convert complex to int

## Copias y vistas de arrays

In [54]:
x = np.arange(10)

In [55]:
y = x

In [56]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
z is x

False

In [60]:
y is x

True

In [61]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [64]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
s = x[0:2, 1:3]
s

array([[1, 2],
       [6, 7]])

In [66]:
s[:] = 5
s

array([[5, 5],
       [5, 5]])

In [67]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [68]:
y

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [69]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Funciones Univeresales (ufunc)
- Unarias: sqrt, sin, cos, **2
- Binarias: maximum, minimum 

In [70]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [73]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [74]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [75]:
alpha = np.linspace(0,2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [76]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [77]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [78]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [79]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [80]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [81]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [82]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [83]:
np.log(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [84]:
np.log2(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [85]:
np.log10(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

$$\sum_{i=1}^n x_i$$

In [86]:
np.sum(x)

45

In [87]:
np.nansum(x)

45

In [88]:
np.prod(x)

0

In [89]:
np.mean(x)

4.5

In [90]:
np.median(x)

4.5

In [91]:
np.min(x)

0

In [92]:
np.max(x)

9

In [93]:
np.std(x)

2.8722813232690143

In [94]:
np.var(x)

8.25

In [95]:
np.argmin(x)

0

In [96]:
np.argmax(x)

9

In [99]:
np.percentile(x, q=0.95)

0.08549999999999999

In [4]:
import numpy as np
y = np.array([True, False, True, True])

In [5]:
np.any(y)

True

In [6]:
# Todos los valores son True o no son 0
np.all(y)

False

In [ ]:
# 
np.random.seed(2019)

In [8]:

z = np.random.random((3,5,5))
z

array([[[0.74856015, 0.38550088, 0.46710238, 0.33370798, 0.20747208],
        [0.75808131, 0.23275579, 0.24889907, 0.78510066, 0.87423573],
        [0.13115169, 0.42522628, 0.32057646, 0.87609572, 0.14587402],
        [0.35040756, 0.05661885, 0.05092056, 0.09473106, 0.03283494],
        [0.02099994, 0.26343497, 0.2342648 , 0.10161051, 0.77149743]],

       [[0.5975708 , 0.84857339, 0.89416494, 0.43900329, 0.6802947 ],
        [0.41730586, 0.70675866, 0.73749952, 0.22462729, 0.58559179],
        [0.84046077, 0.78666957, 0.88412073, 0.96611378, 0.04187274],
        [0.55570213, 0.34580414, 0.49861769, 0.85010493, 0.71899032],
        [0.29421905, 0.85807981, 0.23273534, 0.47675456, 0.27080731]],

       [[0.7477237 , 0.81214188, 0.77366272, 0.92069021, 0.32080839],
        [0.09754631, 0.58277581, 0.37756151, 0.78364143, 0.32536038],
        [0.33128563, 0.99592994, 0.6470856 , 0.0240012 , 0.72545525],
        [0.00409339, 0.76802745, 0.13464442, 0.90759228, 0.7731734 ],
        [0.33087

In [117]:
z.sum()

8.550690063213514

In [9]:
# axis es refereix a la dimensió 
z.sum(axis=0)

array([[2.09385465, 2.04621614, 2.13493004, 1.69340148, 1.20857517],
       [1.27293348, 1.52229025, 1.3639601 , 1.79336938, 1.7851879 ],
       [1.30289808, 2.20782579, 1.8517828 , 1.86621071, 0.913202  ],
       [0.91020308, 1.17045043, 0.68418267, 1.85242827, 1.52499866],
       [0.64609282, 1.86174729, 0.89314148, 1.43615909, 1.90942556]])

In [10]:
z.sum(axis=1)

array([[2.00920065, 1.36353676, 1.32176327, 2.19124593, 2.0319142 ],
       [2.7052586 , 3.54588557, 3.24713823, 2.95660384, 2.29755686],
       [1.51152286, 3.89910758, 2.35909559, 3.49371916, 3.01191824]])

In [11]:
z.sum(axis=2)

array([[2.14234347, 2.89907255, 1.89892418, 0.58551296, 1.39180765],
       [3.45960713, 2.67178311, 3.51923759, 2.96921921, 2.13259606],
       [3.5750269 , 2.16688544, 2.72375762, 2.58753095, 3.22216252]])

# ------

# ALGEBRA LINEAL

In [12]:
row = [1,2,3]

In [14]:
import numpy as np

In [ ]:
#multiplicació de matrius
matrix_result = A.dot(B)

# TASKS

Preguntas de esta tarea


Crea una función que lea una frase de teclado y nos diga si es o no un palíndromo (frase que se lee igual de izquierda a derecha o al revés como por ejemplo La ruta nos aportó otro paso natural.)

Crea un diccionario que tenga por claves los números del 1 al 10 y como valores sus raíces cuadradas

Crea un diccionario que tenga como claves las letras del alfabeto castellano y como valores los símbolos del código morse (los tienes todos en la Wikipedia). A continuación crea un programa que lea una frase del teclado y te la convierta a Morse utilizando el diccionario anterior.

Crea una función que dados dos diccionarios nos diga que claves están presentes en ambos.

Crea una función que dado un número N nos diga si es primo o no (tiene que ir dividiendo por todos los números x comprendidos entre 2 y el propio número N menos uno y ver si el cociente de N/x tiene resto entero o no).

Investiga la documentación de la clase string y crea un método que lea una frase del teclado y escriba la primera letra de cada palabra en Mayúscula.

Crea una función que calcule el máximo común divisor de dos números introducidos por el usuario por teclado.

Investiga el Cifrado del César y crea una función que lo reproduzca en Python. Cada letra del mensaje original se desplaza tres posiciones en el alfabeto estándar. La A se convierte en la D, la B se convierte en la E, la C se convierte en la F... y cuando se acaba el alfabeto se le vuelve a dar la vuelta: la X se convierte en la A, la Y en la B y la X en la C. Los números no sufren ninguna modificación.

Dado una lista de nombres de persona, escribe un algoritmo que los ordene de tres formas diferentes:

A. De forma alfabética

B. De forma alfabética invertida

C. De nombre más corto al más largo.

In [ ]:
#Crea una función que reciba los tres coeficientes a, b y c para resolver una ecuación de segundo grado. 
#Muestra la solución por pantalla y ayúdate de la librería Math para acceder a la función raíz cuadrada.

import cmath

def quadratic_calculation(a, b, c):

    d = (b**2) - (4*a*c)

    # find two solutions
    sol1 = (-b-cmath.sqrt(d))/(2*a)
    sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

In [6]:
def read_pharse():
    frase = input("Escriu un missatge:")
    if frase == frase[::-1]:
        print("És palíndromo")
    else:
        print("No és palíndromo")
        
read_pharse()

Escriu un missatge: 2002


És palíndromo


In [1]:
frase = input("Escriu un missatge:")

Escriu un missatge: Andreu


In [2]:
frase


'Andreu'

In [3]:
frase[::-1]

'uerdnA'

In [10]:
import math

math.sqrt(4)

2.0

In [12]:
dict_quadratic = {}
for t in range(1,11):
    dict_quadratic.setdefault(t, math.sqrt(t))
dict_quadratic

{1: 1.0,
 2: 1.4142135623730951,
 3: 1.7320508075688772,
 4: 2.0,
 5: 2.23606797749979,
 6: 2.449489742783178,
 7: 2.6457513110645907,
 8: 2.8284271247461903,
 9: 3.0,
 10: 3.1622776601683795}

In [ ]:
def cuatro():
    alphabeto ={
        'A':'· —',      
        'B':'— · · ·',      
        'C':'— · — ·',      
        'CH':'— — — —',     
        'D':'— · ·',        
        'E':'·',        
        'F':'· · — ·',      
        'G':'— — ·',        
        'H':'· · · ·',      
        'I':'· ·',      
        'J':'· — — —',      
        'K':'— · —',        
        'L':'· — · ·',      
        'M':'— —',              
        'N':'— ·',      
        'Ñ':'— — · — —',        
        'O':'— — —',        
        'P':'· — — ·',      
        'Q':'— — · —',      
        'R':'· — ·',        
        'S':'· · ·',        
        'T':'—',        
        'U':'· · —',        
        'V':'· · · —',      
        'W':'· — —',        
        'X':'— · · —',      
        'Y':'— · — —',      
        'Z':'— — · ·',      
        '0':'— — — — —',
        '1':'· — — — —',
        '2':'· · — — —',
        '3':'· · · — —',
        '4':'· · · · —',
        '5':'· · · · ·',
        '6':'— · · · ·',
        '7':'— — · · ·',
        '8':'— — — · ·',
        '9':'— — — — ·',
        '/':'— · · — ·',
        '.':'· — · — · —',
        ',':'— — · · — —',
        '?':'· · — — · ·',
        '"':'· — · · — ·'
        }
    
    txt = input("Escriba una palabra: ")
    txt = txt.lower()
    txt = txt.replace(" ","")

    morse = ""
    for x in txt:
        valor = alphabeto.get(x.upper())
        print(valor)
        morse += valor

In [15]:
d = {"a": 1, "b" : 2, "c" : 3}
d_2 = {"a": 1, "e" : 2, "d" : 3}

def check_same_keys_2_dicts(dict_1, dict_2):
    same_keys = [key for key in dict_1 if key in dict_2]
    print(f"The same keys are: {same_keys}")
    
check_same_keys_2_dicts(d, d_2)

The same keys are: ['a']


In [21]:
def is_prime(number):
    for n in range(2, number):
        if number%n != 0:
            return False
    return True

check = is_prime(127)
check

False

In [18]:
4%3

1

In [22]:
frase = "Hola que tal"

In [23]:
h = frase.split(" ")
h

['Hola', 'que', 'tal']

In [25]:
def upper_first_letter_in_phrase(phrase):
    list_words = frase.split(" ")
    for word in list_words:
        print(word[0].upper())

upper_first_letter_in_phrase("hola que tal")

H
Q
T


In [29]:
def maxim_comu_division():
    num1 =int(input("Escribe el primer número"))
    num2 =int(input("Escribe el segundo número"))

    A = max(num1, num2)
    B = min(num1, num2)

    while B:
        mcd = B
        B = A % B
        A = mcd
    mcm =  (num1 * num2) // mcd

    print('El M.C,D de {0} y {1} es {2}'.format(num1, num2, mcd))
    print('El M.C.D de {0} y {1} es {2}'.format(num1, num2, mcm))
    
maxim_comu_division()


Escribe el primer número 54
Escribe el segundo número 94


El M.C,D de 54 y 94 es 2
El M.C.D de 54 y 94 es 2538


In [35]:
list_names = ["Salva", "Andy", "Berta", "Carol"]

In [43]:
list_names.sort(reverse=True)
list_names

['Salva', 'Carol', 'Berta', 'Andreu']

In [37]:
sorted_list

In [41]:
def myFunc(e):
    return len(e)

cars = ['Ford', 'Mitsubishi', 'BMW', 'VW']

cars.sort(key=myFunc)

cars


['VW', 'BMW', 'Ford', 'Mitsubishi']